# Generated by Django 3.1.5 on 2021-01-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='usergroup',
        ),
    ]
