# Generated by Django 3.1.5 on 2021-01-21 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210121_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=django.db.models.fields.NullBooleanField, on_delete=django.db.models.deletion.DO_NOTHING, to='books.series'),
        ),
    ]
