# Generated by Django 3.1.5 on 2021-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210122_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
