# Generated by Django 3.1.5 on 2021-03-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20210325_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
    ]
