# Generated by Django 3.1.5 on 2021-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_author_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='annotation',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
