# Generated by Django 3.1.5 on 2021-06-15 11:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20210615_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhasuser',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
